fastlane_version "2.41.0"

default_platform :ios

platform :ios do

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    increment_build_number
    snapshot
    gym(scheme: "HB3 Trainer")
    testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    increment_build_number
    snapshot
    gym(scheme: "HB3 Trainer")
    deliver
  end

end

